# Generated by Django 5.0.7 on 2024-08-25 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('equip_categroy_id', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='./static/images/categories')),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('equip_model_id', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='./static/images/models')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_model', to='library_app.category')),
            ],
        ),
    ]
