# Generated by Django 5.0.7 on 2024-08-25 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('equip_category_id', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='./static/images/parent_categories')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_categories', to='library_app.category')),
            ],
        ),
        migrations.DeleteModel(
            name='EquipmentModel',
        ),
    ]
