# Generated by Django 5.0.7 on 2024-08-25 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0002_parentcategory_delete_equipmentmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parentcategory',
            name='category',
        ),
    ]
