# Generated by Django 5.0.7 on 2024-08-28 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0005_equipmentmodel_delete_parentcategory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loanrequest',
            fields=[
                ('loanrequestid', models.CharField(db_column='LoanRequestId', max_length=50, primary_key=True, serialize=False)),
                ('loanrequestcode', models.CharField(blank=True, db_column='LoanRequestCode', max_length=50, null=True)),
                ('loanrequeststatusid', models.CharField(blank=True, db_column='LoanRequestStatusId', max_length=50, null=True)),
                ('requestedbyid', models.CharField(blank=True, db_column='RequestedById', max_length=50, null=True)),
                ('requestdate', models.DateTimeField(blank=True, db_column='RequestDate', null=True)),
                ('categoryid', models.CharField(blank=True, db_column='CategoryId', max_length=50, null=True)),
                ('modelid', models.CharField(blank=True, db_column='ModelId', max_length=50, null=True)),
                ('startdate', models.DateTimeField(blank=True, db_column='StartDate', null=True)),
                ('enddate', models.DateTimeField(blank=True, db_column='EndDate', null=True)),
                ('personnelid', models.CharField(blank=True, db_column='PersonnelId', max_length=50, null=True)),
                ('siteid', models.CharField(blank=True, db_column='SiteId', max_length=50, null=True)),
                ('locationid', models.CharField(blank=True, db_column='LocationId', max_length=50, null=True)),
                ('organisationid', models.CharField(blank=True, db_column='OrganisationId', max_length=50, null=True)),
                ('branchid', models.CharField(blank=True, db_column='BranchId', max_length=50, null=True)),
                ('teamid', models.CharField(blank=True, db_column='TeamId', max_length=50, null=True)),
                ('quantity', models.IntegerField(blank=True, db_column='Quantity', null=True)),
                ('loanrequestnotes', models.TextField(blank=True, db_column='LoanRequestNotes', null=True)),
                ('creationdate', models.DateTimeField(blank=True, db_column='CreationDate', null=True)),
                ('modificationdate', models.DateTimeField(blank=True, db_column='ModificationDate', null=True)),
                ('requestedfor', models.CharField(blank=True, db_column='RequestedFor', max_length=255, null=True)),
            ],
            options={
                'db_table': 'LoanRequest',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LoanLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'managed': False},
        ),
    ]
